# Generated by Django 3.2 on 2023-05-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=3000, verbose_name='Write your message here'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='question_categories',
            field=models.CharField(max_length=50, verbose_name='subject'),
        ),
    ]
