# Generated by Django 3.2 on 2023-05-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
